image: atlassian/default-image:2

pipelines:

  branches:
    master:
      - step:
          name: Deploy
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: 'api/'
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}'
                DEBUG: 'true'
                EXTRA_ARGS: '-P 2174'